//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

use crate::rule::Rule;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bangumi")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub season_id: i64,
    pub media_id: i64,
    pub title: String,
    pub cover: String,
    pub evaluate: String,
    pub total: u16,
    pub is_finish: bool,
    pub season_type: u16,
    pub path: String,
    pub created_at: String,
    pub latest_row_at: DateTime,
    pub rule: Option<Rule>,
    pub enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
